server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh    #路由的ID，么有固定规则但是要求唯一，建议配合服务名。
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service #http://localhost:8001    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由。
            - After=2022-10-02T11:46:37.184+08:00[Asia/Shanghai] #断言 在该时间以后才生效
            - Cookie=username,zyy #断言 cookie中带有usernmae并且值为zyy
            - Header=X-Request-Id, \d+ #断言 请求头中要求X-request-Id属性并且值为整数的正则表达式
        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service #http://localhost:8001
          predicates:
            - Path=/payment/lb/**
      discovery:
          locator:
            enabled: true  #开启从注册中心动态生成路由的功能，用微服务名进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示是否将自己注册进eurekaServer,默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true,才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
      #defaultZone: http://localhost:7001/eureka